/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type FaqAccordion = {
  _type: "faqAccordion";
  heading?: string;
  filterCategory?:
    | ""
    | "general"
    | "outdoor-classroom"
    | "volunteering"
    | "donations"
    | "grants";
};

export type TeamGrid = {
  _type: "teamGrid";
  heading?: string;
};

export type FeaturedClasses = {
  _type: "featuredClasses";
  heading?: string;
  limit?: number;
};

export type CtaSection = {
  _type: "ctaSection";
  heading?: string;
  body?: string;
  cta?: Link;
  variant?: "default" | "accent" | "inverted";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type RichText = {
  _type: "richText";
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
  >;
};

export type Hero = {
  _type: "hero";
  heading?: string;
  subheading?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  cta?: Link;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orgName?: string;
  address?: string;
  phone?: string;
  email?: string;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  impactStats?: Array<{
    label?: string;
    value?: string;
    _key: string;
  }>;
  donationUrl?: string;
  newsletterSignupUrl?: string;
  footerText?: string;
  defaultPolicies?: Array<string>;
};

export type Redirect = {
  _id: string;
  _type: "redirect";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  source?: string;
  destination?: string;
  permanent?: boolean;
  isEnabled?: boolean;
};

export type NewsItem = {
  _id: string;
  _type: "newsItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  source?: string;
  url?: string;
  publishedAt?: string;
  excerpt?: string;
};

export type Grower = {
  _id: string;
  _type: "grower";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  location?: string;
  gardenName?: string;
  story?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Partner = {
  _id: string;
  _type: "partner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  url?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  order?: number;
};

export type FaqItem = {
  _id: string;
  _type: "faqItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  category?:
    | "general"
    | "outdoor-classroom"
    | "volunteering"
    | "donations"
    | "grants";
  order?: number;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  pageBuilder?: Array<
    | ({
        _key: string;
      } & Hero)
    | ({
        _key: string;
      } & RichText)
    | ({
        _key: string;
      } & CtaSection)
    | ({
        _key: string;
      } & FeaturedClasses)
    | ({
        _key: string;
      } & TeamGrid)
    | ({
        _key: string;
      } & FaqAccordion)
  >;
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type Link = {
  _type: "link";
  label?: string;
  href?: string;
  newTab?: boolean;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type TeamMemberReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "teamMember";
};

export type BlogPost = {
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
  >;
  author?: TeamMemberReference;
  publishedAt?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  seo?: Seo;
};

export type TeamMember = {
  _id: string;
  _type: "teamMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  bio?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  order?: number;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  date?: string;
  endDate?: string;
  location?: Location;
  eventUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  category?: "dinner" | "springfest" | "fundraiser" | "volunteer" | "other";
  seo?: Seo;
};

export type Location = {
  _type: "location";
  name?: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
};

export type InstructorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "instructor";
};

export type OutdoorClass = {
  _id: string;
  _type: "outdoorClass";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  date?: string;
  endTime?: string;
  ageGroup?: "K-2" | "3-5" | "All Ages" | "Adults";
  category?:
    | "Nature"
    | "Cooking"
    | "Art"
    | "Literacy"
    | "Gardening"
    | "Wildlife";
  price?: number;
  scholarshipAvailable?: boolean;
  maxCapacity?: number;
  instructor?: InstructorReference;
  location?: Location;
  registrationUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  policies?: Array<string>;
  status?: "upcoming" | "full" | "waitlist" | "cancelled" | "completed";
  seo?: Seo;
};

export type Instructor = {
  _id: string;
  _type: "instructor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  bio?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SocialLink = {
  _type: "socialLink";
  platform?: "facebook" | "instagram" | "twitter" | "youtube" | "tiktok";
  url?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | FaqAccordion
  | TeamGrid
  | FeaturedClasses
  | CtaSection
  | SanityImageAssetReference
  | RichText
  | Hero
  | SiteSettings
  | Redirect
  | NewsItem
  | Grower
  | SanityImageCrop
  | SanityImageHotspot
  | Partner
  | FaqItem
  | Page
  | Seo
  | Link
  | Slug
  | TeamMemberReference
  | BlogPost
  | TeamMember
  | Event
  | Location
  | InstructorReference
  | OutdoorClass
  | Instructor
  | SocialLink
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/lib/queries.ts
// Variable: OUTDOOR_CLASSES_QUERY
// Query: *[_type == "outdoorClass" && status in ["upcoming", "full", "waitlist"]    && ($ageGroup == "all" || ageGroup == $ageGroup)    && ($category == "all" || category == $category)  ] | order(date asc) {    _id,    _type,    title,    slug,    date,    endTime,    ageGroup,    category,    price,    scholarshipAvailable,    maxCapacity,    status,    registrationUrl,    image {      ...,      asset-> {        _id,        url,        metadata { lqip, dimensions }      }    },    instructor-> { _id, name, image },    location  }
export type OUTDOOR_CLASSES_QUERY_RESULT = Array<{
  _id: string;
  _type: "outdoorClass";
  title: string | null;
  slug: Slug | null;
  date: string | null;
  endTime: string | null;
  ageGroup: "3-5" | "Adults" | "All Ages" | "K-2" | null;
  category:
    | "Art"
    | "Cooking"
    | "Gardening"
    | "Literacy"
    | "Nature"
    | "Wildlife"
    | null;
  price: number | null;
  scholarshipAvailable: boolean | null;
  maxCapacity: number | null;
  status: "cancelled" | "completed" | "full" | "upcoming" | "waitlist" | null;
  registrationUrl: string | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  instructor: {
    _id: string;
    name: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  } | null;
  location: Location | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: OUTDOOR_CLASS_BY_SLUG_QUERY
// Query: *[_type == "outdoorClass" && slug.current == $slug][0] {    ...,    image {      ...,      asset-> {        _id,        url,        metadata { lqip, dimensions }      }    },    instructor-> { _id, name, bio, image },    "siteSettings": *[_type == "siteSettings"][0] {      defaultPolicies,      donationUrl    }  }
export type OUTDOOR_CLASS_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: "outdoorClass";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  date?: string;
  endTime?: string;
  ageGroup?: "3-5" | "Adults" | "All Ages" | "K-2";
  category?:
    | "Art"
    | "Cooking"
    | "Gardening"
    | "Literacy"
    | "Nature"
    | "Wildlife";
  price?: number;
  scholarshipAvailable?: boolean;
  maxCapacity?: number;
  instructor: {
    _id: string;
    name: string | null;
    bio: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  } | null;
  location?: Location;
  registrationUrl?: string;
  image: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  policies?: Array<string>;
  status?: "cancelled" | "completed" | "full" | "upcoming" | "waitlist";
  seo?: Seo;
  siteSettings: {
    defaultPolicies: Array<string> | null;
    donationUrl: string | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0] {    ...,    socialLinks[]  }
export type SITE_SETTINGS_QUERY_RESULT = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orgName?: string;
  address?: string;
  phone?: string;
  email?: string;
  socialLinks: Array<
    {
      _key: string;
    } & SocialLink
  > | null;
  impactStats?: Array<{
    label?: string;
    value?: string;
    _key: string;
  }>;
  donationUrl?: string;
  newsletterSignupUrl?: string;
  footerText?: string;
  defaultPolicies?: Array<string>;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: EVENTS_QUERY
// Query: *[_type == "event"] | order(date desc) {    _id,    _type,    title,    slug,    date,    endDate,    location,    eventUrl,    category,    image {      ...,      asset-> {        _id,        url,        metadata { lqip, dimensions }      }    }  }
export type EVENTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "event";
  title: string | null;
  slug: Slug | null;
  date: string | null;
  endDate: string | null;
  location: Location | null;
  eventUrl: string | null;
  category:
    | "dinner"
    | "fundraiser"
    | "other"
    | "springfest"
    | "volunteer"
    | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: BLOG_POSTS_QUERY
// Query: *[_type == "blogPost"] | order(publishedAt desc) {    _id,    _type,    title,    slug,    excerpt,    publishedAt,    author-> { name },    image {      ...,      asset-> {        _id,        url,        metadata { lqip, dimensions }      }    }  }
export type BLOG_POSTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "blogPost";
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  publishedAt: string | null;
  author: {
    name: string | null;
  } | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: FAQ_ITEMS_QUERY
// Query: *[_type == "faqItem"] | order(order asc) {    _id,    _type,    question,    answer,    category  }
export type FAQ_ITEMS_QUERY_RESULT = Array<{
  _id: string;
  _type: "faqItem";
  question: string | null;
  answer: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  category:
    | "donations"
    | "general"
    | "grants"
    | "outdoor-classroom"
    | "volunteering"
    | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: TEAM_MEMBERS_QUERY
// Query: *[_type == "teamMember"] | order(order asc) {    _id,    _type,    name,    role,    bio,    image {      ...,      asset-> {        _id,        url,        metadata { lqip, dimensions }      }    }  }
export type TEAM_MEMBERS_QUERY_RESULT = Array<{
  _id: string;
  _type: "teamMember";
  name: string | null;
  role: string | null;
  bio: string | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "outdoorClass" && status in ["upcoming", "full", "waitlist"]\n    && ($ageGroup == "all" || ageGroup == $ageGroup)\n    && ($category == "all" || category == $category)\n  ] | order(date asc) {\n    _id,\n    _type,\n    title,\n    slug,\n    date,\n    endTime,\n    ageGroup,\n    category,\n    price,\n    scholarshipAvailable,\n    maxCapacity,\n    status,\n    registrationUrl,\n    image {\n      ...,\n      asset-> {\n        _id,\n        url,\n        metadata { lqip, dimensions }\n      }\n    },\n    instructor-> { _id, name, image },\n    location\n  }\n': OUTDOOR_CLASSES_QUERY_RESULT;
    '\n  *[_type == "outdoorClass" && slug.current == $slug][0] {\n    ...,\n    image {\n      ...,\n      asset-> {\n        _id,\n        url,\n        metadata { lqip, dimensions }\n      }\n    },\n    instructor-> { _id, name, bio, image },\n    "siteSettings": *[_type == "siteSettings"][0] {\n      defaultPolicies,\n      donationUrl\n    }\n  }\n': OUTDOOR_CLASS_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "siteSettings"][0] {\n    ...,\n    socialLinks[]\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "event"] | order(date desc) {\n    _id,\n    _type,\n    title,\n    slug,\n    date,\n    endDate,\n    location,\n    eventUrl,\n    category,\n    image {\n      ...,\n      asset-> {\n        _id,\n        url,\n        metadata { lqip, dimensions }\n      }\n    }\n  }\n': EVENTS_QUERY_RESULT;
    '\n  *[_type == "blogPost"] | order(publishedAt desc) {\n    _id,\n    _type,\n    title,\n    slug,\n    excerpt,\n    publishedAt,\n    author-> { name },\n    image {\n      ...,\n      asset-> {\n        _id,\n        url,\n        metadata { lqip, dimensions }\n      }\n    }\n  }\n': BLOG_POSTS_QUERY_RESULT;
    '\n  *[_type == "faqItem"] | order(order asc) {\n    _id,\n    _type,\n    question,\n    answer,\n    category\n  }\n': FAQ_ITEMS_QUERY_RESULT;
    '\n  *[_type == "teamMember"] | order(order asc) {\n    _id,\n    _type,\n    name,\n    role,\n    bio,\n    image {\n      ...,\n      asset-> {\n        _id,\n        url,\n        metadata { lqip, dimensions }\n      }\n    }\n  }\n': TEAM_MEMBERS_QUERY_RESULT;
  }
}
